### ISSUE TITLE
bgcolor not supported in react

### ISSUE THREAD

**Issue by jeongsd** [chromakode/react-html-email#1]
bgcolor not work

and i can't found bgcolor attribute in react document
https://facebook.github.io/react/docs/tags-and-attributes.html

https://github.com/facebook/react/issues/140

**Comment by chromakode** [comment]
Hi Jeong,

Are you calling `ReactHTMLEmail.injectReactEmailAttributes` before your React code? It should modify React to accept `bgcolor`. Is it not working for you?

**Comment by jeongsd** [comment]
oh sorry it' work!!
this program really helpful me

thank you @chromakode  Have a nice day~

**Comment by chromakode** [comment]
Great, glad to hear it! Thanks for the update. :)
