### ISSUE TITLE
Warnings in console of production

### ISSUE THREAD

**Issue by SashaRudolf** [chromakode/react-html-email#14]
I have a series of errors coming from some padding on a span, and some other minor warnings. However, I am fine with those styles not being rendered.

Could we add a config variable that would disable the warnings in production?

**Comment by Roilan** [comment]
@SashaRudolf Yes, you have a good point. We run into similar issues when running it in production and clogs up our logs. How do you feel about just checking for the `production` env variable? Thoughts @chromakode

**Comment by chromakode** [comment]
Yeah checking `NODE_ENV` is a good idea!

**Comment by Roilan** [comment]
I'll see if I have some time this week to make the PR.

**Comment by chromakode** [comment]
It was supposed to be possible to disable these with something like:

```js
ReactHTMLEmail.configStyleValidator({
  strict: false,
  warn: process.NODE_ENV === 'production',
})
```

However it appears that there is a bug where the value of `warn` isn't taken into consideration. We should probably change the defaults to above as well.

**Comment by SashaRudolf** [comment]
@Roilan @chromakode Sounds awesome, anyone had any time to work on this?
