### ISSUE TITLE
Problem with React 15.3.0

### ISSUE THREAD

**Issue by mfeuermann** [chromakode/react-html-email#17]
Hello 

thanks for your library!

If you generate email with your sample app

**It seems there is problem with react 15.3.0**

W20160819-08:49:36.187(2)? (STDERR) Warning: Unknown props `bgcolor`, `border`, `align`, `valign` on <table> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
W20160819-08:49:36.188(2)? (STDERR)     in table (created by Box)
W20160819-08:49:36.189(2)? (STDERR)     in Box (created by Email)
W20160819-08:49:36.189(2)? (STDERR)     in body (created by Email)
W20160819-08:49:36.189(2)? (STDERR)     in html (created by Email)
W20160819-08:49:36.190(2)? (STDERR)     in Email
W20160819-08:49:36.196(2)? (STDERR) Warning: validateDOMNesting(...): <table> cannot appear as a child of <tbody>. See Email > Box > tbody > Box > table.

Can you check it please  ?
Thank you

**Comment by chromakode** [comment]
Thanks for the heads-up! I am currently traveling, but will take a look into this soon. We probably need to inject additional properties in https://github.com/chromakode/react-html-email/blob/master/src/injectReactEmailAttributes.js

**Comment by chromakode** [comment]
Hey @mfeuermann, sorry for the slow follow-up. I suspect this may be happening because `injectReactEmailAttributes()` hasn't been called. I was able to reproduce the react attributes warning by omitting it, and the warning went away when I added it. If that doesn't solve your problem, could you please share the script that you are running? Thanks!

**Comment by mfeuermann** [comment]
Hi @chromakode, i check my code and found problem in my code with injectReactEmailAttributes. In this moment its working fine! Thank you for support!

**Comment by chromakode** [comment]
Great glad to hear it! Thanks for the update :smile:
