### ISSUE TITLE
ClassName on Item

### ISSUE THREAD

**Issue by martinbethann** [chromakode/react-html-email#23]
I was hoping to have ClassName added to the Item component.  I see it listed as a prop but it will not render on the element like it does with Box.

Thank you!

**Comment by chromakode** [comment]
Good idea! Would you be interested in making a pull request to add it here? https://github.com/chromakode/react-html-email/blob/master/src/components/Item.js

**Comment by chromakode** [comment]
https://github.com/chromakode/react-html-email/pull/24
