### ISSUE TITLE
<Email /> bodyStyle props

### ISSUE THREAD

**Issue by lulalachen** [chromakode/react-html-email#31]
Hello
I found that I needed to pass styles into `<body />` tag when I was using `<Email />` component
and I'm wondering if you might open a new prop `bodyStyle` to handle styling body.

Thanks for this great email library

All the Best

**Comment by lulalachen** [comment]
I wish I can help with this PR, if you found it a good idea, then I'll start working on it.

**Comment by chromakode** [comment]
Thanks for the suggestion! I would gladly accept this in a PR. :+1:

**Comment by lulalachen** [comment]
I've filed PR here #32
