### ISSUE TITLE
Include 'dowload' attribute on <A> component

### ISSUE THREAD

**Issue by jmaguirrei** [chromakode/react-html-email#34]
Hi, is it possible to include this attribute?

Like `<A href="..." download="my-file.pdf" />`

So the user can click the link and download the pdf on the link, instead of open it.

Thanks

**Comment by chromakode** [comment]
Merged in https://github.com/chromakode/react-html-email/commit/3529d461640e5c31b3c442f81ffded3bf50f3d6e :+1:
