### ISSUE TITLE
Latest React PropTypes is deprecated - use npm Proptype package

### ISSUE THREAD

**Issue by centinel3** [chromakode/react-html-email#37]
I just installed and am using this awesome package and noticed that I'm getting a react warning about proptypes:

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

I took a look at the code and it looks like the native React.PropTypes is being used. Any way you could update this to use the npm prop-type package now? React is deprecating this in the near future.

Let me know when you can. Thanks! -Chris

**Comment by chromakode** [comment]
Fixed in https://github.com/chromakode/react-html-email/commit/c1d9dc558f78423eddec5c8bdb54294f8e6ea806. :+1:
