### ISSUE TITLE
Your kitchenSink.jsx doesn't work, should it?

### ISSUE THREAD

**Issue by jacksonp2008** [chromakode/react-html-email#45]
Appears import should be 'react-html-email', and some others.

I just pasted into a brand new create-react-app, and doesn't seem to work.

Looking to render emails from various sources.

thanks

**Comment by chromakode** [comment]
The import is relative because `kitchenSink.jsx` is [tested in CI after every commit](https://github.com/chromakode/react-html-email/blob/master/examples/kitchenSink.jsx). Does the code work when you change the import? Can you share more information about the error you are getting?
