### ISSUE TITLE
unsupported props warning even when downgrading to 1.2.0

### ISSUE THREAD

**Issue by ticruz38** [chromakode/react-html-email#46]
```
Warning: Unknown props `bgcolor`, `border`, `align`, `valign` on <table> tag. Remove these props from the element
```
I keep getting this message, also passing any of those props has no effect to Box or Email component.
I am using react 15 in my project so I downgraded the library but still meeting those issues.

**Comment by chromakode** [comment]
Since you downgraded you'll need to run `injectReactEmailAttributes()` for these props to work in React 15. See the [README for 2.0.1](https://github.com/chromakode/react-html-email/blob/v2.0.1/README.md) for more info. Does this resolve the problem?

**Comment by ticruz38** [comment]
yes thank you
