### ISSUE TITLE
Capability to add media queries

### ISSUE THREAD

**Issue by davidhouweling** [chromakode/react-html-email#5]
Referring to [Email Boilerplate template](https://github.com/seanpowell/Email-Boilerplate/blob/master/email.html) I'd like to be able to do mobile targetting such as HDI images.

Looking at [Email component](https://github.com/chromakode/react-html-email/blob/master/src/components/Email.js) there doesn't appear to be anything at present to allow for the injection? Perhaps I'm missing something?

Extending to this, I would also like to be able to do some of the more quirky things like `@font-face` as well.

**Comment by chromakode** [comment]
Yeah we should add a "headCSS" prop to the `Email` component which gets inserted into a style tag. Would you be interested in drafting a pull request?

**Comment by chromakode** [comment]
Just pushed https://github.com/chromakode/react-html-email/commit/58fdc5a437e143bb6b6669f7231dd48073e97ecd which includes an example for how to accomplish this. :+1:
