### ISSUE TITLE
Webpack build error

### ISSUE THREAD

**Issue by brave-merida** [chromakode/react-html-email#50]
Hi,
I am using this package.
When I build my react project with webpack, it gets an error.
```
node_modules/eslint-config-airbnb/rules/react.js:
        Configuration for rule "react/jsx-boolean-value" is invalid:
        Value "never,[object Object]" should NOT have more than 1 items.
```

**Comment by brave-merida** [comment]
fixed: I removed rc* files and kinds of stuff.

**Comment by kopax** [comment]
https://github.com/chromakode/react-html-email/blob/master/.babelrc#L5

I have made a browser compatible version of the 3.0.0 of `react-html-mail` : 

https://www.npmjs.com/package/react-html-email-browser

All I did was to change the target.
