### ISSUE TITLE
is there a full example

### ISSUE THREAD

**Issue by dewelloper** [chromakode/react-html-email#56]
Hello i couldnt create with this example becouse it doesnt make any sence.
I have made a component according the example and that gave me just a page that is writen download source code.. etc.

import React from 'react'

import {
  render
} from 'react-dom';
//import { Email, Item, Span, A, renderEmail } from 'react-html-email'
import { Box, Email, Image, Item, Span, A } from 'react-html-email'

//import eml from './XEmail'

const css = `
@media only screen and (max-device-width: 480px) {
  font-size: 20px !important;
}`.trim()

const sourceURL = 'https://raw.githubusercontent.com/chromakode/react-html-email/master/examples/kitchenSink.js'

export const Connect = () => (
  <Email title="Test Email" headCSS={css}>
    <Item>
      <Span fontSize={15}>Hello, world!</Span>
    </Item>
    <Item>
      <Box cellSpacing={20} width="100%" style={{ borderTop: '3px solid black' }}>
        <Item>
          <Span color="gray" lineHeight={20}>Generated by <A href="https://github.com/chromakode/react-html-email">react-html-email</A></Span>
          <Image data-mc-bar="bar" data-mc-baz="baz" alt="react" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/React.js_logo.svg/100px-React.js_logo.svg.png" width={100} height={100} />
          <A download={sourceURL} href={sourceURL}>Source code</A>
        </Item>
      </Box>
    </Item>
  </Email>
)

export default Connect

**Comment by neo182** [comment]
@dewelloper same here...!

**Comment by Khangeldy** [comment]
[Article in Medium](https://medium.com/readme-mic/creating-and-sending-reusable-emails-with-react-a80ade7614b)
